USE [master]
GO
/****** Object:  Database [DavidVendingMachine]    Script Date: 3/24/2018 12:34:00 PM ******/
CREATE DATABASE [DavidVendingMachine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DavidVendingMachine', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DavidVendingMachine.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DavidVendingMachine_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DavidVendingMachine_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DavidVendingMachine] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DavidVendingMachine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DavidVendingMachine] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET ARITHABORT OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DavidVendingMachine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DavidVendingMachine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DavidVendingMachine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DavidVendingMachine] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DavidVendingMachine] SET  MULTI_USER 
GO
ALTER DATABASE [DavidVendingMachine] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DavidVendingMachine] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DavidVendingMachine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DavidVendingMachine] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [DavidVendingMachine] SET  READ_WRITE 
GO
