USE [DavidVendingMachine]
GO
/****** Object:  Table [dbo].[Change]    Script Date: 4/8/2018 4:33:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Change](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[Quarters] [int] NOT NULL,
	[Dimes] [int] NOT NULL,
	[Nickels] [int] NOT NULL,
	[Pennies] [int] NOT NULL,
 CONSTRAINT [PK_Change] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
