USE [DavidVendingMachine]
GO
/****** Object:  Table [dbo].[ItemInventories]    Script Date: 4/8/2018 4:33:09 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ItemInventories](
	[ID] [int] NOT NULL,
	[ItemsID] [int] NOT NULL,
 CONSTRAINT [PK_ItemInventories] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
